# Generated by Django 3.2 on 2021-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meaning', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'word',
                'verbose_name_plural': 'words',
            },
        ),
    ]
