# Generated by Django 3.2 on 2021-06-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meaning', models.CharField(blank=True, max_length=255, null=True)),
                ('example', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'expression',
                'verbose_name_plural': 'expressions',
            },
        ),
    ]
