# Generated by Django 3.2 on 2021-07-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expression', '0002_alter_expression_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
