# Generated by Django 3.2 on 2021-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('past', models.CharField(max_length=200)),
                ('present', models.CharField(max_length=200)),
                ('future', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'verb',
                'verbose_name_plural': 'verbs',
            },
        ),
    ]
